name: Semiconductor Daily Digest

on:
  workflow_dispatch:
  schedule:
    # Run at both 15:00 and 16:00 UTC, then gate to 08:00 America/Los_Angeles in-job.
    # Handles PST (UTC-8) and PDT (UTC-7).
    - cron: '0 15 * * *'
    - cron: '0 16 * * *'

jobs:
  send-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run only at 8:00 AM Pacific
        id: pacific_time_gate
        shell: bash
        run: |
          HOUR=$(TZ=America/Los_Angeles date +%H)
          if [ "$HOUR" != "08" ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "Skipping run: current Pacific hour is $HOUR"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
            echo "Proceeding: current Pacific hour is 08"
          fi

      - name: Send daily digest
        if: steps.pacific_time_gate.outputs.skip == 'false'
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: |
          python semiconductor_digest.py --run-once
